---
- name: Update apt cache for Debian.
  apt: update_cache=yes #cache_valid_time=86400
  changed_when: false

- name: Ensure nginx is installed for Debian.
  apt:
    name: "{{ nginx_package_name }}"
    state: present
    default_release: "{{ nginx_default_release }}"
