---
- name: Install nginx
  hosts: staging_servers_ALL 
  become: yes
  vars_files:
    - vars/Vhosts-80.yml
    - vars/php-fpm.yml
  roles:
    - nginx
  tasks:
    - name: Activate config from Nginx
      shell: | 
        cp /etc/nginx/sites-enabled/{{ server_name }}-80.conf /etc/nginx/sites-available/{{ server_name }}-80.conf
        ln -sf /etc/nginx/sites-available/{{ server_name }}-80.conf /etc/nginx/sites-enabled/{{ server_name }}-80.conf
        systemctl restart nginx

- name: Install PHP Wordpress Mysql
  hosts: staging_servers_ALL 
  become: yes
  vars_files:
    - vars/Vhosts-80.yml
    - vars/php-fpm.yml
  roles:
    - mysql
    - wordpress
    - php
