---
- name: Install LEMP and Wordpress
  hosts: staging_servers_ALL
  become: yes
  vars_files:
    - vars/Vhosts-80.yml

  pre_tasks:
  - name: Include PHP packages (If Debian)
    include_vars:
      file: vars/Debian-php-packages.yml
    when: ansible_os_family == "Debian"

  - name: Include PHP packages (If RedHat)
    include_vars:
      file: vars/RedHat-php-packages.yml
    when: ansible_os_family == "RedHat"

  roles:
    - nginx
    - mysql
    - wordpress
    - php


