---
- name: Install LEMP and Wordpress
  hosts: staging_servers_ALL
  become: yes
  vars_files:
    - vars/wordpress-80/main.yml

  pre_tasks:
  - name: Include vars for Debian (If Debian)
    include_vars:
      dir: vars/wordpress-80/setup-Debian
      extensions:
        - 'yml'
    when: ansible_os_family == "Debian"

  - name: Include vars for RedHat (If RedHat)
    include_vars:
      dir: vars/wordpress-80/setup-RedHat
      extensions:
        - 'yml'
    when: ansible_os_family == "RedHat"

  roles:
    - nginx
    - mysql
    - wordpress
    - php


