---
# tasks file for wordpress

# WordPress Configuration
- name: create /var/www/{{ server_name }} directory for unarchiving
  file:
    path: /var/www/{{ server_name }}
    state: directory

- name: Download and unpack latest WordPress
  unarchive:
    creates: "/var/www/{{ server_name }}/wordpress"
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ server_name }}"
    remote_src: yes
#    creates: "/var/www/{{ server_name }}/wordpress"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ server_name }}/wordpress/ -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ server_name }}/wordpress/ -type f -exec chmod 640 {} \\;"

- name: Set up wp-config
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/{{ server_name }}/wordpress/wp-config.php"

