---
- name: Set ownership
  file:
    path: "/var/www/{{ server_name }}"
    state: directory
    recurse: yes
    owner: "{{ wp_owner }}" # nginx | www-data
    group: "{{ wp_group }}" # nginx | www-data
